### ISSUE TITLE
self.last_known_heartbeat.items() 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by chuanqichen** [raokrutarth/manufacturing-os#133]
`
pythonw main.py --num_types 7 --nodes_per_type 5  --run_test_ops True --failure_rate 10 --recover_rate 10   --update_dep_rate 3 --log_level Critical
......

CRITICAL  23:10:02 production-stage-12 sc_stage.py:429::_attempt_manufacture_cycle | Node 12 successfully manufactured batch ItemReq(Item(type:4, id:4-AFBTR756), qty:1) which is a finale item
CRITICAL  23:10:03 ops-runner   ops_generator.py:58::recover_node         | Node 5 to be recovered
CRITICAL  23:10:03 test ops runner-5 sc_stage.py:196::restart              | Node 5's stage is being restarted
CRITICAL  23:10:06 ops-runner   ops_generator.py:48::kill_node            | Node 0 to be killed
CRITICAL  23:10:06 test ops runner-0 sc_stage.py:180::stop                 | Node 0's stage is being stopped
Exception in thread heartbeat-0:
Traceback (most recent call last):
  File "/Users/chuanqi/opt/anaconda3/envs/cs244b/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/threads.py", line 163, in run
    self.send_message_for_dead_nodes()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/threads.py", line 126, in send_message_for_dead_nodes
    dead_node_ids = self.node_process.detect_and_fetch_dead_nodes()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/processes.py", line 163, in detect_and_fetch_dead_nodes
    for nid, lt in self.last_known_heartbeat.items():
AttributeError: 'NoneType' object has no attribute 'items'

Exception in thread subscriber-0:
Traceback (most recent call last):
  File "/Users/chuanqi/opt/anaconda3/envs/cs244b/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/threads.py", line 58, in run
    self.node_process.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/processes.py", line 133, in onMessage
    self.msg_handler.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 391, in onMessage
    return self.callbacks[message.type][message.action](message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 472, in on_heartbeat_resp
    self.node_process.update_heartbeat(message.source)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/processes.py", line 153, in update_heartbeat
    self.last_known_heartbeat[node_id] = curr_time
TypeError: 'NoneType' object does not support item assignment

`

**Comment by nishantrai18** [comment]
Fixed in new PR
