### ISSUE TITLE
sc_stage _mark_request_complete has KeyError at self.pending_requests.remove(response.request_id) 

### ISSUE THREAD

**Issue by chuanqichen** [raokrutarth/manufacturing-os#141]
`python main.py --num_types 5 --nodes_per_type 2  --failure_rate 0 --recover_rate 0 --update_dep_rate 4 | grep -e "death"                                                                                 (base) 
Exception in thread subscriber-5:
Traceback (most recent call last):
  File "/Users/chuanqi/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/threads.py", line 40, in run
    self.node_process.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/processes.py", line 148, in onMessage
    self.msg_handler.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 397, in onMessage
    return self.callbacks[message.type][message.action](message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 429, in on_item_sent_resp
    self.sc_stage.process_batch_request_response(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/sc_stage.py", line 348, in process_batch_request_response
    self._mark_request_complete(response)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/sc_stage.py", line 226, in _mark_request_complete
    self.pending_requests.remove(response.request_id)
KeyError: '8833eb74'
`

**Comment by chuanqichen** [comment]
`
python main.py --num_types 5 --nodes_per_type 2  --failure_rate 0 --recover_rate 0 --update_dep_rate 0 | grep -e "death"    

chuanqi@Chuanqis-iMac ~/P/c/m/src (master)> python main.py --num_types 5 --nodes_per_type 2  --failure_rate 0 --recover_rate 0 --update_dep_rate 0 | grep -e "death"                                                                                 (base) 
Exception in thread subscriber-0:
Traceback (most recent call last):
  File "/Users/chuanqi/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/threads.py", line 40, in run
    self.node_process.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/processes.py", line 148, in onMessage
    self.msg_handler.onMessage(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 397, in onMessage
    return self.callbacks[message.type][message.action](message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/messages.py", line 451, in on_item_waiting_resp
    self.sc_stage.process_item_waiting_response(message)
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/sc_stage.py", line 231, in process_item_waiting_response
    curr_status = self.outbound_log[batch]
  File "/Users/chuanqi/Projects/cs244b/manufacturing-os/src/file_dict.py", line 39, in __getitem__
    raise KeyError
KeyError
`
